
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address:true
eureka.client.register-with-eureka: true
eureka.client.service-url.defaultZone= http://eureka-1:8762/eureka/ , http://eureka-2:8763/eureka/

